apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: clusters
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  # Everything from this repo will be run in this cluster. You trust me right?
  repo: "https://github.com/capi-samples/fosdem-24.git"
  branch: proxmox
  insecureSkipTLSVerify: true
  paths:
  - crs
  - clusters